apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - deployment.yaml

images:
  - name: nginx-image
    newName: johnmanjiro13/gitops-app
    newTag: release-hogehoge
